{% set name = "olas" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/olas-{{ version }}.tar.gz
  sha256: b039f02eea41dfba30445b3a50c20b5278d8a2fe0ccb948847e2daf6f74a2290

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - cartopy >=0.18.0,<0.19.0
    - dask >=2021.3.0,<2022.0.0
    - matplotlib-base >=3.3.4,<4.0.0
    - netcdf4 >=1.5.6,<2.0.0
    - numpy >=1.20.1,<2.0.0
    - python >=3.6,<4.0
    - xarray >=0.17.0,<0.18.0

test:
  imports:
    - olas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jorgeperezg/olas
  summary: Library with wave tools like ESTELA
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jorgeperezg
